# Translations template for networking-powervm.
# Copyright (C) 2015 ORGANIZATION
# This file is distributed under the same license as the networking-powervm
# project.
# Automatically generated, 2015.
#
msgid ""
msgstr ""
"Project-Id-Version: networking-powervm 0.0.1.dev93\n"
"Report-Msgid-Bugs-To: EMAIL@ADDRESS\n"
"POT-Creation-Date: 2015-10-06 14:03-0500\n"
"PO-Revision-Date: 2015-10-06 14:03-0500\n"
"Last-Translator: Automatically generated\n"
"Language-Team: none\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=utf-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Generated-By: Babel 2.0\n"

#: networking_powervm/plugins/ibm/agent/powervm/agent_base.py:47
msgid ""
"The number of seconds agent will wait between polling when exception is "
"caught"
msgstr ""
"El número de segundos que el agente esperará entre sondeos cuando se capture una "
"excepción"

#: networking_powervm/plugins/ibm/agent/powervm/agent_base.py:50
#: networking_powervm/plugins/ibm/agent/powervm/fake_sea_agent.py:46
msgid ""
"The number of seconds the agent will wait between polling for local "
"device changes."
msgstr ""
"El número de segundos que el agente esperará entre el sondeo para los cambios de "
"dispositivo local."

#: networking_powervm/plugins/ibm/agent/powervm/agent_base.py:53
msgid ""
"The number of seconds the agent should wait between heal/optimize "
"intervals.  Should be higher than the polling_interval as it runs in the "
"nearest polling loop."
msgstr ""
"El número de segundos que el agente esperará entre intervalos de "
"recuperación/optimización. Debe ser mayor que el polling_interval porque se "
"ejecuta en el bucle de sondeo más próximo."

#: networking_powervm/plugins/ibm/agent/powervm/agent_base.py:212
msgid "Failed reporting state!"
msgstr "Se ha encontrado un error al informar del estado."

#: networking_powervm/plugins/ibm/agent/powervm/exceptions.py:21
#, python-format
msgid "Expected exactly one host; found %(host_count)d"
msgstr "Se esperaba exactamente un solo host; se han encontrado %(host_count)d"

#: networking_powervm/plugins/ibm/agent/powervm/exceptions.py:25
msgid ""
"There are no network bridges (ex. Shared Ethernet Adapters) on the "
"system.  Can not start the Neutron agent."
msgstr ""
"No hay puentes de red (por ejemplo, adaptadores Ethernet compartidos) en el "
"sistema. No se puede iniciar el agente Neutron."

#: networking_powervm/plugins/ibm/agent/powervm/exceptions.py:30
msgid ""
"The system has more than one network bridge, but the bridge_mappings have"
" not been specified.  Please configure the bridge_mappings before "
"proceeding."
msgstr ""
"El sistema tiene más de un puente de red, pero no se ha especificado"
" bridge_mappings. Configure bridge_mappings antes de "
"continuar."

#: networking_powervm/plugins/ibm/agent/powervm/exceptions.py:36
#, python-format
msgid ""
"Device %(dev)s on Virtual I/O Server %(vios)s was not found.  Unable to "
"set up physical network %(phys_net)s."
msgstr ""
"No se ha encontrado el dispositivo %(dev)s en el servidor de E/S virtual %(vios)s. No se "
"puede configurar la red física %(phys_net)s."

